### ISSUE TITLE
ISearchCommentsResponse matches property type interface

### ISSUE THREAD

**Issue by JimmyAppelt** [baileyherbert/envato.js#7]
Hi 🙂, thanks for the great lib!

It seems that I get an array of `ItemConversation` instead of `ItemComment` on a search comments response.
https://github.com/baileyherbert/envato.js/blob/master/src/endpoints/catalog.ts#L190

**Comment by baileyherbert** [comment]
Hi, thanks for reporting this! I hope my little mistake didn't cause you too much trouble... 😅
I just released a fix as version `3.0.5`. Let me know if you have any issues & cheers!

**Comment by JimmyAppelt** [comment]
@baileyherbert my pleasure 🙂 
Thank you for fixing it so fast, cheers!

**Comment by JimmyAppelt** [comment]
@baileyherbert I just see that `ItemComment` `id` should be a number https://github.com/baileyherbert/envato.js/blob/0cd7ea5f182d6f3b1f8d8c191e9283c1f90bccb3/src/types/api.ts#L164

**Comment by baileyherbert** [comment]
Aaahh!!! Another one? How embarrassing, don't look! 😱😱😱

Let me go through those types in detail real quick and verify everything, and then I will release version `3.0.6` haha

**Comment by JimmyAppelt** [comment]
@baileyherbert found one more 🙂 (but ofc we can pass the id as string here)
https://github.com/baileyherbert/envato.js/blob/0cd7ea5f182d6f3b1f8d8c191e9283c1f90bccb3/src/types/options.ts#L199

**Comment by baileyherbert** [comment]
Alright, I fixed a lot of little mistakes and `3.0.6` is now published. 👍

With respect to the `item_id` property, I'm going to keep it as `string | number` for now (to ensure backwards compatibility) and will remove the string in the next major update.

**Comment by JimmyAppelt** [comment]
@baileyherbert thank you 🙂
